### ISSUE TITLE
Can Preface blow the stack?

### ISSUE THREAD

**Issue by UnixJunkie** [xvw/preface#117]
Or is it safe to use in production code (i.e. code than can potentially handle a lot of data).

**Comment by xvw** [comment]
To be very honest... we don't know... 
It is common knowledge that Free (Monad/Applicative/Selective) and to a lesser extent Freer are greedy but it seems to me that the other implementations are quite idiomatic. Maybe the best thing would be to give it a try? We'd love to hear your feedback!

**Comment by UnixJunkie** [comment]
In other words, are you careful of implementing only tail-recursive
algorithms?
And, if not do you at least clearly mention it in the documentation for
each function?

**Comment by xvw** [comment]
I think the only two modules involved are List and Nonempty_list and it seems to me that the functions are tail-recursive. Other module, ie: Foldable, depends on the implementation of the minimal interfaces you give.

**Comment by UnixJunkie** [comment]
Ok, I might give a try at preface some day!

**Comment by xvw** [comment]
Nice, feel free to give us feedback and thanks for your interest!
