### ISSUE TITLE
Meet Semi Lattice

### ISSUE THREAD

**Issue by gr-im** [xvw/preface#149]
A **Meet Semi Lattice** capture the notion of a set with "greatest lower bound"

**Operation**
- `val meet : t -> t -> t`

**Laws**:
- **associativity** :  `meet a (meet b c) = meet (meet a b) c`
- **commutativity**: `meet a b = meet b a` 
- **idempotency**: `meet a a = a` 

**Suggested incarnation**:
- `Bool`

**Comment by Hakimba** [comment]
Hi, those Meet Semi Lattice are very new to me, but the notion capturated isn't the _"greatest lower bound"_ instead of _"least lower bound"_ ? As the dual of **Meet Semi Lattice**, the **Join Semi Lattice**, capture the notion of "least upper bound"

**Comment by xhtmlboi** [comment]
Yes you are right! It is fixed.
