### ISSUE TITLE
Divisible's minimal definitions

### ISSUE THREAD

**Issue by arbipher** [xvw/preface#171]
`Divisible` is the dual of `Applicative`.

Would it be fine to add similar minimal [definitions](https://ocaml-preface.github.io/preface/Preface_specs/Divisible/index.html#minimal-definition) in `Divisible` that are duals of [those](https://ocaml-preface.github.io/preface/Preface_specs/Applicative/index.html#minimal-definition) in `Applicative`

**Comment by gr-im** [comment]
Hi, thanks for your feedback!
I'm not sure it would add "much" because the Contravariant part of Preface doesn't offer direct symmetry with Applicative (and Alternative). Do you think it really brings a lot of clarification and is it worth it?

**Comment by arbipher** [comment]
Fine, after your reply and checking with the code, I think I made a mistake.

My original concern is on `lift2` and `product`. In `Applicative`, `product` is defined in each minimal definition. I didn't see it in `Divisible`.
However, with utop I can see they are both in the module `API`s.
